### PR TITLE
Migrate to cats-effect 3.x and fs2 3.x

### PR DESCRIPTION
**Pull request by RafalSumislawski**
This PR migrates `fs2-mqtt` to the latest `cats-effect` and `fs2` versions. This of course breaks compatibility with CE2 and fs2 2.x.

Problems:
- I converted the `LocalPublisher` example from Monix to ZIO as Monix doesn't support CE3.
- [ ] I rewrote the `TickerSpec` to use the `TestControl` from CE3, but the test doesn't work. The `Ticker` itself seems to work just fine, so it must have something to do with my inability to use the `TestControl` properly.
- [ ] In `Transport` I had some issues caused by the removal of timeouts and `close` from fs2's `Socket`.

### CODE REVIEW

**Comment by fcabestre** [comment]
This is a bit of a pleasant surprise. To tell the truth I've neglected this small project for a while. This was due to my inability to understand how a Scala library maintainer should manage bumping fundamental dependencies like `cats-effect`. 

When I decided to support `Scala3`, I wanted `fs2-mqtt` available for `Scala2` as well and this was quite an easy task. But how do people from `fs2`for example handle compatibility with both `cats-effect` 2 & 3? I mean do they say up to version `x` it goes with `cats-effect` 2, and from version `y` it goes with `cats-effect` 3? 

I also really wanted to keep an example using `Monix` along with `ZIO`. For me this was all the point of going `tagless final` using only `cats-effect` type classes. But anyway, if `Monix` doesn't support `fs2 3.x`...  ¯\\_(ツ)\_/¯

**Comment by RafalSumislawski** [comment]
The situation with CE2 to CE3 migration is rough. There is no way to "cross-compile" one codebase to CE2 and CE3. The two approaches I see out in the wild are:
1. Use CE2 until version X. Use CE3 starting from X+1 and never look back.
  Examples:
    - cats-retry uses CE2 until 2.1.1 and CE3 starting from 3.0.0
    - pureconfig-cats-effect uses CE2 until 0.14.1 and CE3 starting from 0.15.0
2. Keep maintaining a CE2 seriess/branch. While developing new stuff on CE3.
  Examples:
    - fs2 3.x uses CE3 and all new development happens on that version, but fs2 2.5.x which supports CE2 keeps getting bugfix releases
    - http4s 0.23.x uses CE3 and 0.22.x uses CE2. They are maintained and released in pararell. 0.22.x gets all the bugfixes, and some of the new stuff, but not all of it.
    
Two exampels for each may not be much, but you can see a pattern. 1. is taken by small libraries, or libraries which don't have CE at their core (they just integrate with it). Approach 2. is taken by large libraries at the core of the ecosystem, which have large user-bases taking long time to migrate, and which have the maintainer capacity to support two (or more in case of http4s) branches.

The monix situation is unclear. It may support CE3 one day (https://github.com/monix/monix/issues/1502). But I can imagine the migration effort is dounting. 

IMO tagless-final is still worth it. There's at least `IO` and `ZIO` that are compatibile with it, and when Monix caches up it will be too.

It's your library, so if you prefer to stay on CE2 longer, because you need it in you project etc. I'll understand and I won't push ;). I needed MQTT in my CE3 project, so I had to do the legwork anyway. Once it was done, PRing it was a natural consequence.

**Comment by fcabestre** [comment]
I'm really happy you've done all the work to go CE3 and I've no personal use of a CE2 version. It was more a project about learning stuff like how to write a purely functional effecting library, using tagless final or how to manage such a thing in the Scala ecosystem. 

I'm not sure either if anyone anywhere is using it as it is today. So as you've found an interest in it, I'll be of course happy to merge your work. I'll do then a major release and some extra work at least to use `IO` on one of the examples.

**Comment by fcabestre** [comment]
I've figured out how to fix the `TickerSpec`! As it's said in the `CE3` documentation `TestControl` should be seen as a kind of debugger to step through the fiber's activation. As the ticker is based on 1 second ticks, to go through the tests we have "step" many times, and I've introduced a helper function for that.

I've rewritten the example previously based on `Monix` with `IO` which is an immediate adaptation. Zero effort in comparison with `ZIO`.

I've merged your PR into master by hand, so I'll close it without further ceremony. Thanks a lot for your help.

**Pull request closed without merging**
